import { PROVIDER_LABEL, PROVIDER_SHORT, RISK_LABEL, WORKER_STATUS_LABEL, confidencePercent } from "@/lib/format";
import type { DataOrigin, Provider, Risk, WorkerStatus } from "@/lib/types";

const PROVIDER_INK: Record<Provider, string> = {
  aws: "text-aws border-aws/35",
  azure: "text-azure border-azure/35",
  gcp: "text-gcp border-gcp/35",
};

export function ProviderMark({
  provider,
  full = false,
}: {
  provider: Provider;
  full?: boolean;
}) {
  return (
    <span
      className={`inline-flex items-center rounded-xs border bg-surface px-1.5 py-0.5 text-[0.6875rem] font-semibold uppercase tracking-[0.06em] ${PROVIDER_INK[provider]}`}
    >
      {full ? PROVIDER_LABEL[provider] : PROVIDER_SHORT[provider]}
    </span>
  );
}

const RISK_STYLE: Record<Risk, string> = {
  low: "border-rule text-ink-soft bg-surface",
  medium: "border-caution/40 text-caution bg-caution-tint",
  high: "border-brand-edge text-brand bg-brand-tint",
};

export function RiskTag({ risk }: { risk: Risk }) {
  return (
    <span
      className={`inline-flex items-center rounded-xs border px-1.5 py-0.5 text-[0.6875rem] font-medium ${RISK_STYLE[risk]}`}
    >
      {RISK_LABEL[risk]}
    </span>
  );
}

const WORKER_STYLE: Record<WorkerStatus, string> = {
  ok: "text-verified",
  partial: "text-caution",
  failed: "text-brand",
  skipped: "text-ink-mute",
};

export function WorkerStatusText({ status }: { status: WorkerStatus }) {
  return <span className={WORKER_STYLE[status]}>{WORKER_STATUS_LABEL[status]}</span>;
}

export function Tag({
  children,
  tone = "neutral",
}: {
  children: React.ReactNode;
  tone?: "neutral" | "caution" | "brand" | "savings";
}) {
  const styles = {
    neutral: "border-rule text-ink-soft bg-surface",
    caution: "border-caution/40 text-caution bg-caution-tint",
    brand: "border-brand-edge text-brand bg-brand-tint",
    savings: "border-savings/35 text-savings bg-savings-tint",
  } as const;
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-xs border px-1.5 py-0.5 text-[0.6875rem] font-medium ${styles[tone]}`}
    >
      {children}
    </span>
  );
}

/**
 * Confidence is a scored judgement, not a measurement, so it reads as discrete
 * ticks rather than a continuous bar that would imply false precision.
 */
export function ConfidenceMeter({ value }: { value: number }) {
  const ticks = 10;
  const filled = Math.round(value * ticks);
  return (
    <span className="inline-flex items-center gap-2">
      <span
        className="flex gap-[2px]"
        role="meter"
        aria-valuenow={Math.round(value * 100)}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label="Confidence"
      >
        {Array.from({ length: ticks }, (_, index) => (
          <span
            key={index}
            className={`h-3 w-[3px] rounded-[1px] transition-colors duration-300 ${
              index < filled ? "bg-brand" : "bg-rule"
            }`}
          />
        ))}
      </span>
      <span className="num text-[0.8125rem] text-ink">{confidencePercent(value)}</span>
    </span>
  );
}

/**
 * Three origins, not two. `upload` is somebody's real bill that CloudCause
 * measured but did not verify, and reading it as `live` would be a lie.
 */
const ORIGIN_STYLE: Record<DataOrigin, string> = {
  fixture: "text-ink-mute",
  upload: "text-caution",
  live: "text-verified",
};

const ORIGIN_LABEL: Record<DataOrigin, string> = {
  fixture: "fixture",
  upload: "your upload",
  live: "live",
};

export function OriginText({ origin }: { origin: DataOrigin }) {
  return (
    <span className={ORIGIN_STYLE[origin]} title={ORIGIN_TITLE[origin]}>
      {ORIGIN_LABEL[origin]}
    </span>
  );
}

const ORIGIN_TITLE: Record<DataOrigin, string> = {
  fixture: "Synthetic demo data generated by this repository",
  upload: "A cost export you supplied: measured by CloudCause, not verified against a cloud account",
  live: "Read from a provider API through a read-only connector",
};

export function SectionHeading({
  children,
  aside,
}: {
  children: React.ReactNode;
  aside?: React.ReactNode;
}) {
  return (
    <div className="mb-3 flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
      <h2 className="font-display text-[1.35rem] leading-tight text-ink">{children}</h2>
      {aside ? <div className="text-xs text-ink-mute">{aside}</div> : null}
    </div>
  );
}
