"""CloudCause shared contracts.

Every service (gateway, ADK orchestrator, Strands AWS worker, MAF Azure worker,
UI) speaks these models. Versioned so a UI can be replaced without a rewrite.
"""

from .analytics import (
    AnalyticsConfig,
    AnomalyCandidate,
    DailyTotal,
    Dimension,
    PeriodComparison,
    ProviderComparison,
    Reconciliation,
)
from .common import (
    DATA_ORIGINS,
    PROVIDERS,
    SUPPORTED_FOCUS_VERSION,
    CloudCauseModel,
    DataOrigin,
    DateRange,
    Provenance,
    Provider,
    Risk,
    SourceResult,
    SupportStatus,
    reconcile_origin,
    utcnow,
)
from .datasets import (
    ACCEPTED_CONTENT_TYPES,
    DATASET_SOURCE_KINDS,
    SOURCE_KIND_EVIDENCE_TYPES,
    DatasetCreated,
    DatasetIngestReport,
    DatasetRowRejection,
    DatasetSourceKind,
    DatasetSourceSummary,
    DatasetSummary,
)
from .gateway import GatewayHealth, InvestigationCreated, ScenarioSummary
from .investigation import (
    ErrorResponse,
    Evidence,
    Finding,
    InvestigationPlan,
    InvestigationRequest,
    InvestigationStatus,
    ProgressEvent,
    ProviderStatus,
    ProviderTask,
    WorkerRequest,
    WorkerResponse,
    WorkerStatus,
    determine_effective_agent_mode,
    resolve_agent_mode,
)
from .knowledge import (
    BillingRule,
    KnowledgeProvenance,
    RuleCitation,
    RuleQueryResult,
    RuleSource,
    RuleType,
)
from .provider_data import (
    AuditEvent,
    ChargeCategory,
    CloudResource,
    CostRecord,
    FocusRecord,
    MetricPoint,
    MetricSeries,
    ProviderDataBundle,
    Recommendation,
)
from .rendering import report_headline, report_to_markdown
from .report import (
    REPORT_CONTRACT_VERSION,
    InvestigationReport,
    InvestigationState,
    ValidationIssue,
    ValidationSeverity,
)
from .settings import (
    AgentMode,
    DataMode,
    HistoryBackend,
    Settings,
    find_repo_root,
    get_settings,
    load_env_file,
)

__all__ = [
    "ACCEPTED_CONTENT_TYPES",
    "AgentMode",
    "AnalyticsConfig",
    "AnomalyCandidate",
    "AuditEvent",
    "BillingRule",
    "ChargeCategory",
    "CloudCauseModel",
    "CloudResource",
    "CostRecord",
    "DATASET_SOURCE_KINDS",
    "DATA_ORIGINS",
    "DailyTotal",
    "DataMode",
    "DataOrigin",
    "DatasetCreated",
    "DatasetIngestReport",
    "DatasetRowRejection",
    "DatasetSourceKind",
    "DatasetSourceSummary",
    "DatasetSummary",
    "DateRange",
    "Dimension",
    "ErrorResponse",
    "Evidence",
    "Finding",
    "FocusRecord",
    "GatewayHealth",
    "HistoryBackend",
    "InvestigationPlan",
    "InvestigationCreated",
    "InvestigationReport",
    "InvestigationRequest",
    "InvestigationState",
    "InvestigationStatus",
    "KnowledgeProvenance",
    "MetricPoint",
    "MetricSeries",
    "PROVIDERS",
    "PeriodComparison",
    "ProgressEvent",
    "Provenance",
    "Provider",
    "ProviderComparison",
    "ProviderDataBundle",
    "ProviderStatus",
    "ProviderTask",
    "REPORT_CONTRACT_VERSION",
    "Recommendation",
    "Reconciliation",
    "Risk",
    "RuleCitation",
    "RuleQueryResult",
    "RuleSource",
    "RuleType",
    "SOURCE_KIND_EVIDENCE_TYPES",
    "SUPPORTED_FOCUS_VERSION",
    "Settings",
    "ScenarioSummary",
    "SourceResult",
    "SupportStatus",
    "ValidationIssue",
    "ValidationSeverity",
    "WorkerRequest",
    "WorkerResponse",
    "WorkerStatus",
    "determine_effective_agent_mode",
    "find_repo_root",
    "get_settings",
    "load_env_file",
    "reconcile_origin",
    "report_headline",
    "report_to_markdown",
    "resolve_agent_mode",
    "utcnow",
]
